version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: .dockerfiles/apiDev
    ports:
      - "9000:9000"
    volumes:
      - ./api:/opt/app
    restart: always

  db:
    build:
      context: ./
      dockerfile: .dockerfiles/db
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
